"""delete count days

Revision ID: 7c339c172e51
Revises: 660f83a10f47
Create Date: 2025-04-19 19:13:59.928553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c339c172e51'
down_revision: Union[str, None] = '660f83a10f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'count_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('count_days', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
